from __future__ import annotations

from typing import Any, Dict


DISEASE_CONFIG: Dict[str, Dict[str, Any]] = {
    "stroke": {
        "display_name": "Stroke Risk",
        "dataset_filename": "healthcare-dataset-stroke-data.csv",
        "target_column": "stroke",
        "classification_threshold": 0.7,
        "feature_columns": [
            "gender",
            "age",
            "hypertension",
            "heart_disease",
            "ever_married",
            "work_type",
            "Residence_type",
            "avg_glucose_level",
            "bmi",
            "smoking_status",
        ],
        "numeric_columns": [
            "age",
            "hypertension",
            "heart_disease",
            "avg_glucose_level",
            "bmi",
        ],
        "categorical_columns": [
            "gender",
            "ever_married",
            "work_type",
            "Residence_type",
            "smoking_status",
        ],
        "defaults": {
            "gender": "Unknown",
            "age": 45.0,
            "hypertension": 0,
            "heart_disease": 0,
            "ever_married": "No",
            "work_type": "Private",
            "Residence_type": "Urban",
            "avg_glucose_level": 100.0,
            "bmi": 25.0,
            "smoking_status": "never smoked",
        },
        "explanation_rules": [
            {
                "field": "age",
                "operator": "gte",
                "value": 60,
                "label": "Advanced age",
                "message": "Older age is associated with higher stroke risk.",
            },
            {
                "field": "hypertension",
                "operator": "eq",
                "value": 1,
                "label": "Hypertension",
                "message": "High blood pressure is a major contributor to stroke risk.",
            },
            {
                "field": "heart_disease",
                "operator": "eq",
                "value": 1,
                "label": "Heart disease history",
                "message": "Existing cardiovascular disease raises stroke risk.",
            },
            {
                "field": "avg_glucose_level",
                "operator": "gte",
                "value": 140,
                "label": "High glucose",
                "message": "High glucose may indicate metabolic stress linked to stroke risk.",
            },
            {
                "field": "bmi",
                "operator": "gte",
                "value": 30,
                "label": "High BMI",
                "message": "Obesity increases the likelihood of vascular complications.",
            },
        ],
    },
    "diabetes": {
        "display_name": "Diabetes Risk",
        "dataset_filename": "diabetes_prediction_dataset.csv",
        "target_column": "diabetes",
        "feature_columns": [
            "gender",
            "age",
            "hypertension",
            "heart_disease",
            "smoking_history",
            "bmi",
            "HbA1c_level",
            "blood_glucose_level",
        ],
        "numeric_columns": [
            "age",
            "hypertension",
            "heart_disease",
            "bmi",
            "HbA1c_level",
            "blood_glucose_level",
        ],
        "categorical_columns": [
            "gender",
            "smoking_history",
        ],
        "defaults": {
            "gender": "Unknown",
            "age": 45.0,
            "hypertension": 0,
            "heart_disease": 0,
            "smoking_history": "never",
            "bmi": 25.0,
            "HbA1c_level": 5.7,
            "blood_glucose_level": 110.0,
        },
        "explanation_rules": [
            {
                "field": "HbA1c_level",
                "operator": "gte",
                "value": 6.5,
                "label": "Elevated HbA1c",
                "message": "HbA1c above the normal range is strongly associated with diabetes.",
            },
            {
                "field": "blood_glucose_level",
                "operator": "gte",
                "value": 140,
                "label": "High blood glucose",
                "message": "Increased glucose values can indicate impaired sugar regulation.",
            },
            {
                "field": "bmi",
                "operator": "gte",
                "value": 30,
                "label": "High BMI",
                "message": "High BMI is a known risk factor for type 2 diabetes.",
            },
            {
                "field": "hypertension",
                "operator": "eq",
                "value": 1,
                "label": "Hypertension",
                "message": "Hypertension often coexists with metabolic syndrome.",
            },
        ],
    },
    "kidney": {
        "display_name": "Chronic Kidney Disease Risk",
        "dataset_filename": "kidney_disease_dataset.csv",
        "target_column": "Target",
        "target_negative_values": ["No_Disease"],
        "feature_columns": [
            "Age of the patient",
            "Blood pressure (mm/Hg)",
            "Specific gravity of urine",
            "Albumin in urine",
            "Sugar in urine",
            "Random blood glucose level (mg/dl)",
            "Blood urea (mg/dl)",
            "Serum creatinine (mg/dl)",
            "Sodium level (mEq/L)",
            "Potassium level (mEq/L)",
            "Hemoglobin level (gms)",
            "Hypertension (yes/no)",
            "Diabetes mellitus (yes/no)",
            "Appetite (good/poor)",
            "Pedal edema (yes/no)",
            "Anemia (yes/no)",
            "Estimated Glomerular Filtration Rate (eGFR)",
            "Smoking status",
            "Body Mass Index (BMI)",
        ],
        "numeric_columns": [
            "Age of the patient",
            "Blood pressure (mm/Hg)",
            "Specific gravity of urine",
            "Albumin in urine",
            "Sugar in urine",
            "Random blood glucose level (mg/dl)",
            "Blood urea (mg/dl)",
            "Serum creatinine (mg/dl)",
            "Sodium level (mEq/L)",
            "Potassium level (mEq/L)",
            "Hemoglobin level (gms)",
            "Estimated Glomerular Filtration Rate (eGFR)",
            "Body Mass Index (BMI)",
        ],
        "categorical_columns": [
            "Hypertension (yes/no)",
            "Diabetes mellitus (yes/no)",
            "Appetite (good/poor)",
            "Pedal edema (yes/no)",
            "Anemia (yes/no)",
            "Smoking status",
        ],
        "defaults": {
            "Age of the patient": 45.0,
            "Blood pressure (mm/Hg)": 120.0,
            "Specific gravity of urine": 1.02,
            "Albumin in urine": 0.0,
            "Sugar in urine": 0.0,
            "Random blood glucose level (mg/dl)": 110.0,
            "Blood urea (mg/dl)": 35.0,
            "Serum creatinine (mg/dl)": 1.0,
            "Sodium level (mEq/L)": 138.0,
            "Potassium level (mEq/L)": 4.5,
            "Hemoglobin level (gms)": 13.5,
            "Hypertension (yes/no)": "no",
            "Diabetes mellitus (yes/no)": "no",
            "Appetite (good/poor)": "good",
            "Pedal edema (yes/no)": "no",
            "Anemia (yes/no)": "no",
            "Estimated Glomerular Filtration Rate (eGFR)": 90.0,
            "Smoking status": "no",
            "Body Mass Index (BMI)": 24.0,
        },
        "explanation_rules": [
            {
                "field": "Serum creatinine (mg/dl)",
                "operator": "gte",
                "value": 1.3,
                "label": "High creatinine",
                "message": "Elevated creatinine can indicate impaired kidney filtration.",
            },
            {
                "field": "Estimated Glomerular Filtration Rate (eGFR)",
                "operator": "lte",
                "value": 60,
                "label": "Reduced eGFR",
                "message": "A reduced eGFR is a key sign of kidney dysfunction.",
            },
            {
                "field": "Blood pressure (mm/Hg)",
                "operator": "gte",
                "value": 140,
                "label": "High blood pressure",
                "message": "Elevated blood pressure can damage kidney blood vessels over time.",
            },
            {
                "field": "Hemoglobin level (gms)",
                "operator": "lte",
                "value": 11,
                "label": "Low hemoglobin",
                "message": "Anemia is commonly associated with chronic kidney disease.",
            },
        ],
    },
    "heart": {
        "display_name": "Heart Disease Risk",
        "dataset_filename": "heart.csv",
        "target_column": "target",
        "feature_columns": [
            "age",
            "sex",
            "cp",
            "trestbps",
            "chol",
            "fbs",
            "restecg",
            "thalach",
            "exang",
            "oldpeak",
            "slope",
            "ca",
            "thal",
        ],
        "numeric_columns": [
            "age",
            "sex",
            "cp",
            "trestbps",
            "chol",
            "fbs",
            "restecg",
            "thalach",
            "exang",
            "oldpeak",
            "slope",
            "ca",
            "thal",
        ],
        "categorical_columns": [],
        "defaults": {
            "age": 45.0,
            "sex": 1,
            "cp": 0,
            "trestbps": 120.0,
            "chol": 200.0,
            "fbs": 0,
            "restecg": 0,
            "thalach": 150.0,
            "exang": 0,
            "oldpeak": 1.0,
            "slope": 1,
            "ca": 0,
            "thal": 2,
        },
        "explanation_rules": [
            {
                "field": "trestbps",
                "operator": "gte",
                "value": 140,
                "label": "High resting blood pressure",
                "message": "Raised blood pressure is associated with higher cardiac risk.",
            },
            {
                "field": "chol",
                "operator": "gte",
                "value": 240,
                "label": "High cholesterol",
                "message": "High cholesterol may contribute to plaque build-up in arteries.",
            },
            {
                "field": "oldpeak",
                "operator": "gte",
                "value": 2.0,
                "label": "Elevated ST depression",
                "message": "Higher oldpeak values may reflect exercise-induced cardiac stress.",
            },
        ],
    },
}


def get_supported_diseases() -> list[str]:
    return list(DISEASE_CONFIG.keys())
